baseURL: "https://arjun-kk.github.io" 
title: Arjun Krishna Kumar
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20


taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
       # - name: Books
        #  url: books/
        #  weight: 5 
        #- name: Papers
         # url: papers/
         # weight: 2
        - name: Teaching
          url: teaching/
          weight: 2 
        #- name: Courses
         # url: courses/
         # weight: 3
        # - name: Data
         # url: data/
         # weight: 4 
        #- name: Blog
         # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
         # weight: 6

params:
    description: "I am a doctoral student in philosophy at UF."
    author: Arjun Krishna Kumar
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arjun Krishna Kumar
          subtitle: "I am a PhD student in the Department of Philosophy at the University of Florida. I work on issues at the intersection of the philosophy of mind, philosophy of science and AI."
          imageUrl: "AIGeneratedPhilCogMap.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Philosophical Thinking
          buttons:
            - name: Research
              url: research/
            #- name: Papers
            #  url: papers/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            - name: Teaching
              url: teaching/
            #- name: Courses
            #  url: courses/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: CV (New Format).pdf
        - name: Email
          url: mailto:arjun948@gmail.com
        - name: orcid
          url: https://orcid.org/0009-0000-4779-2031
        - name: philpeople
          url: https://philpeople.org/profiles/arjun-krishna-kumar
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/arjun-kk
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        #- name: Twitter
        #  url: https://x.com/pmichaillat
        #- name: Bluesky
        #  url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableHLJS: true
        disableScrollBarStyle: true

        favicon: "/philosopher.png"
        favicon16x16: "/philosopher.png"
        favicon32x32: "/philosopher.png"
        apple_touch_icon: "/philosopher.png"
        mask_icon: "/philosopher.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Arjun Krishna Kumar"
      icon: philosopher.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
